import { createHash } from 'node:crypto';

import type { Repositories } from '@immunograph/database';
import { z } from 'zod';

import type { ArtifactStore } from './artifact-store.js';
import { DependencyUnavailableError } from './errors.js';
import { isFallbackEligible } from './execution-policy.js';
import type { McpToolGateway } from './mcp-tool-gateway.js';
import type { ReportGenerationCommand, ReportGenerationPort } from './ports.js';
import { createSupplementalReportArtifacts } from './report-artifacts.js';

const sha256 = z.string().regex(/^[a-f0-9]{64}$/);
const reportDataSchema = z.object({
  artifacts: z
    .array(
      z.object({
        artifactId: z.string().min(1),
        mediaType: z.string().min(1),
        sha256,
        byteLength: z.number().int().nonnegative(),
        reference: z.string().min(1),
        contentBase64: z.string().min(1).optional(),
      }),
    )
    .min(1),
  disclaimer: z.string().min(1),
  provenanceSummary: z.record(z.unknown()),
  runQuality: z.string().min(1),
});
const researchPackageDataSchema = z
  .object({
    artifact: z.object({
      artifactId: z.string().min(1),
      mediaType: z.literal('application/zip'),
      sha256,
      byteLength: z.number().int().nonnegative(),
      reference: z.string().min(1),
      contentBase64: z.string().min(1),
    }),
    requiredSections: z.array(z.string().min(1)).min(1),
    includesCsvExports: z.literal(true),
    includesAgentTrace: z.boolean(),
  })
  .strict();

const SYNTHETIC_REPORT_DISCLAIMER =
  'This analysis was produced using the deterministic offline demonstration workflow. Binding scores generated by synthetic predictors are for software demonstration only and must not be interpreted as validated scientific predictions.';

type ReportRepositories = Pick<
  Repositories,
  | 'runs'
  | 'projects'
  | 'proteins'
  | 'candidates'
  | 'rankingResults'
  | 'predictorExecutions'
  | 'observations'
  | 'populationCoverageResults'
  | 'shortlistOptimizationResults'
  | 'approvals'
  | 'artifacts'
  | 'events'
  | 'graphEdges'
  | 'graphNodes'
  | 'stages'
>;

export class McpReportGenerationPort implements ReportGenerationPort {
  constructor(
    private readonly repositories: ReportRepositories,
    private readonly artifactStore: ArtifactStore,
    private readonly gateway: McpToolGateway,
    private readonly fallback: ReportGenerationPort,
  ) {}

  assertAvailable(): Promise<void> {
    return Promise.resolve();
  }

  async generate(command: ReportGenerationCommand) {
    try {
      const run = await this.repositories.runs.findById(command.runId);
      if (run === null) throw new DependencyUnavailableError('report run');
      const snapshotHash = await this.repositories.rankingResults.findLatestSnapshotHash(
        command.runId,
      );
      if (snapshotHash === null) throw new DependencyUnavailableError('ranking snapshot');
      const rankings = await this.repositories.rankingResults.findSnapshot(
        command.runId,
        snapshotHash,
      );
      const [project, protein] = await Promise.all([
        this.repositories.projects.findById(run.projectId),
        this.repositories.proteins.findById(run.proteinInputId),
      ]);
      if (project === null) throw new DependencyUnavailableError('report project');
      if (protein === null) throw new DependencyUnavailableError('report protein');
      const rows = [];
      const details = [];
      for (const ranking of rankings) {
        const detail = await this.repositories.candidates.findDetail(
          command.runId,
          ranking.candidateId,
          snapshotHash,
        );
        if (detail === null) continue;
        details.push(detail);
        const statuses = detail.candidate.predictionObservations.map(
          ({ predictorExecution }) => predictorExecution.sourceStatus,
        );
        rows.push({
          rank: ranking.rank,
          track: ranking.track,
          peptide: detail.candidate.peptide,
          start: detail.candidate.start,
          end: detail.candidate.end,
          allele: detail.candidate.allele,
          finalScore: ranking.finalScore,
          category: ranking.category,
          sourceStatus: statuses.join('+'),
          scientificUse: statuses.length > 0 && statuses.every((status) => status === 'LIVE'),
        });
      }
      const executionMode = run.executionMode ?? 'FIXTURE';
      const scientificUse = executionMode === 'LIVE';
      const disclaimer = scientificUse
        ? 'Computational predictions require independent scientific validation before research or clinical interpretation.'
        : SYNTHETIC_REPORT_DISCLAIMER;
      const response = await this.gateway.call(
        'generate_report',
        {
          runId: command.runId,
          templateVersion: command.options.templateVersion,
          outputFormats: command.options.formats,
          idempotencyKey: command.requestId,
          reportSnapshot: {
            executionMode,
            runQuality: run.quality ?? 'PARTIAL',
            scientificUse,
            disclaimer,
            candidates: rows,
          },
        },
        reportDataSchema,
        { runId: command.runId, requestId: command.requestId },
      );
      const created = [];
      const suffix = command.requestId.replace(/[^a-zA-Z0-9-]/g, '').slice(0, 36) || 'mcp';
      for (const [index, artifact] of response.data.artifacts.entries()) {
        if (artifact.contentBase64 === undefined) {
          throw new DependencyUnavailableError('MCP report artifact content');
        }
        const bytes = Buffer.from(artifact.contentBase64, 'base64');
        if (
          bytes.byteLength !== artifact.byteLength ||
          createHash('sha256').update(bytes).digest('hex') !== artifact.sha256
        ) {
          throw new DependencyUnavailableError('MCP report artifact integrity');
        }
        const format = command.options.formats[index];
        if (format === undefined) throw new DependencyUnavailableError('MCP report format');
        const relativePath = `${command.runId}/report-${snapshotHash.slice(0, 12)}-${suffix}.${format.toLowerCase()}`;
        const file = await this.artifactStore.write(
          relativePath,
          bytes.toString('utf8'),
          artifact.mediaType,
        );
        created.push(
          await this.repositories.artifacts.create({
            runId: command.runId,
            type: format,
            format,
            ...file,
            templateVersion: command.options.templateVersion,
          }),
        );
      }
      await createSupplementalReportArtifacts(this.repositories, this.artifactStore, {
        runId: command.runId,
        rankingSnapshotHash: snapshotHash,
        requestSuffix: suffix,
        templateVersion: command.options.templateVersion,
        includeEvidenceGraph: command.options.includeEvidenceGraph,
        includeWorkflowTrace: command.options.includeWorkflowTrace,
      });
      const packageResponse = await this.gateway.call(
        'export_research_package',
        {
          runId: command.runId,
          idempotencyKey: command.requestId,
          includeStructure: true,
          includeChemistry: true,
          includeDocking: true,
          includeAgentTrace: true,
          packageSnapshot: await this.createPackageSnapshot({
            run,
            project,
            protein,
            rows,
            details,
            snapshotHash,
            disclaimer,
          }),
        },
        researchPackageDataSchema,
        { runId: command.runId, requestId: command.requestId },
      );
      const packageBytes = Buffer.from(packageResponse.data.artifact.contentBase64, 'base64');
      if (
        packageBytes.byteLength !== packageResponse.data.artifact.byteLength ||
        createHash('sha256').update(packageBytes).digest('hex') !==
          packageResponse.data.artifact.sha256
      ) {
        throw new DependencyUnavailableError('MCP research package artifact integrity');
      }
      const packageFile = await this.artifactStore.writeBytes(
        `${command.runId}/research-package-${snapshotHash.slice(0, 12)}-${suffix}.zip`,
        packageBytes,
        'application/zip',
      );
      await this.repositories.artifacts.create({
        runId: command.runId,
        type: 'RESEARCH_PACKAGE',
        format: 'ZIP',
        ...packageFile,
        templateVersion: command.options.templateVersion,
      });
      const first = created[0];
      if (first === undefined) throw new DependencyUnavailableError('MCP report output');
      return { artifactJobId: first.id, status: 'QUEUED' as const };
    } catch (error) {
      if (!isFallbackEligible(error)) throw error;
      return this.fallback.generate(command);
    }
  }

  private async createPackageSnapshot(input: {
    run: {
      id: string;
      executionMode: string | null;
      quality: string | null;
      configurationJson: string;
    } & Record<string, unknown>;
    project: Record<string, unknown>;
    protein: {
      id: string;
      originalFasta: string;
      normalizedSequence: string;
      sequenceLength: number;
      sha256: string;
      header: string;
      validationProfileVersion: string;
      createdAt: Date;
    } & Record<string, unknown>;
    rows: Array<Record<string, unknown>>;
    details: Array<{
      candidate: {
        id: string;
        peptide: string;
        predictionObservations: Array<{
          id?: string;
          candidateId?: string;
          predictorExecution?: Record<string, unknown>;
        }>;
        constraintOutcomes?: Array<{ id?: string }>;
        evidenceSummaries?: Array<{ id?: string }>;
      } & Record<string, unknown>;
    }>;
    snapshotHash: string;
    disclaimer: string;
  }) {
    const [
      candidates,
      predictorExecutions,
      observations,
      populationCoverage,
      shortlistOptimizations,
      approvals,
      graphNodes,
      graphEdges,
      stages,
      events,
    ] = await Promise.all([
      this.repositories.candidates.listByRun(input.run.id),
      this.repositories.predictorExecutions.listByRun(input.run.id),
      this.repositories.observations.listByRun(input.run.id),
      this.repositories.populationCoverageResults.listByRun(input.run.id),
      this.repositories.shortlistOptimizationResults.listByRun(input.run.id),
      this.repositories.approvals.listByRun(input.run.id),
      this.repositories.graphNodes.listByRun(input.run.id),
      this.repositories.graphEdges.listByRun(input.run.id),
      this.repositories.stages.listByRun(input.run.id),
      this.repositories.events.listByRun(input.run.id),
    ]);
    const provenance = mergeProvenance(predictorExecutions, input.details);
    const ranked: Array<Record<string, unknown>> = input.rows.map((row) => ({
      ...row,
      candidate: plainRecord(
        candidates.find((candidate: { id: string }) => candidate.id === row.candidateId),
      ),
    }));
    return {
      project: plainRecord(input.project),
      run: plainRecord(input.run),
      configuration: parseJson(input.run.configurationJson),
      originalFasta: input.protein.originalFasta,
      normalizedSequence: {
        id: input.protein.id,
        header: input.protein.header,
        normalizedSequence: input.protein.normalizedSequence,
        sequenceLength: input.protein.sequenceLength,
        sha256: input.protein.sha256,
        validationProfileVersion: input.protein.validationProfileVersion,
        createdAt: input.protein.createdAt.toISOString(),
      },
      inputChecksums: {
        originalFasta: createHash('sha256').update(input.protein.originalFasta).digest('hex'),
        normalizedSequence: createHash('sha256')
          .update(input.protein.normalizedSequence)
          .digest('hex'),
        recordedProteinSha256: input.protein.sha256,
      },
      predictions: {
        mhci: predictionBundle('MHCI', observations, candidates, provenance),
        mhcii: predictionBundle('MHCII', observations, candidates, provenance),
        bcell: predictionBundle('BCELL', observations, candidates, provenance),
        populationCoverage: populationCoverage.map(plainRecord),
        connectorProvenance: provenance,
      },
      candidates: {
        ranked,
        shortlisted: ranked.filter((row) => row.category === 'RECOMMENDED'),
        rejected: ranked.filter((row) => row.category === 'REJECTED'),
        evidenceLinks: candidateEvidenceLinks(input.details),
        csv: candidatesCsv(input.rows),
      },
      structure: {
        structures: [],
        epitopeStructureMap: [],
        surfaceAccessibility: [],
        structureConfidence: [],
      },
      compounds: {
        compounds: [],
        descriptors: [],
        ligandPreparation: [],
      },
      docking: {
        receptorPdbqt: `REMARK ImmunoGraph persisted export receptor placeholder\nREMARK runId ${input.run.id}\n`,
        ligandPdbqt: `REMARK ImmunoGraph persisted export ligand placeholder\nREMARK runId ${input.run.id}\n`,
        dockingOutputPdbqt: `REMARK ImmunoGraph persisted export docking placeholder\nREMARK runId ${input.run.id}\n`,
        dockingPoses: [],
        dockingSummary: { runId: input.run.id, sourceStatus: 'ABSTAINED' },
        dockingProvenance: { runId: input.run.id, status: 'ABSTAINED' },
      },
      construct: {
        fasta: constructFasta(input.run.id, ranked),
        json: {
          schemaVersion: 'immunograph-construct.v1',
          runId: input.run.id,
          selectedCandidateIds: ranked
            .filter((row) => row.category === 'RECOMMENDED')
            .map((row) => row.candidateId),
        },
        optimization: shortlistOptimizations.map(plainRecord),
      },
      evidence: {
        evidenceGraph: { nodes: graphNodes.map(plainRecord), edges: graphEdges.map(plainRecord) },
        workflowTrace: { stages: stages.map(plainRecord), events: events.map(plainRecord) },
        agentTrace: { steps: events.map(plainRecord) },
        approvals: approvals.map(plainRecord),
        auditEvents: events.map(plainRecord),
      },
      reports: {
        summaryMarkdown: `# ImmunoGraph Report\n\nRun: ${input.run.id}\n\n${input.disclaimer}\n`,
        report: {
          schemaVersion: 'immunograph-report.v1',
          runId: input.run.id,
          executionMode: input.run.executionMode,
          quality: input.run.quality,
          rankingSnapshotHash: input.snapshotHash,
          candidates: input.rows,
          connectorProvenance: provenance,
        },
        limitationsMarkdown: `# Limitations\n\n${input.disclaimer}\n`,
        reportCsv: candidatesCsv(input.rows),
      },
    };
  }
}

function plainRecord(value: unknown): Record<string, unknown> {
  if (value === null || value === undefined) return {};
  return JSON.parse(
    JSON.stringify(value, (_key, item: unknown) => (item instanceof Date ? item.toISOString() : item)),
  ) as Record<string, unknown>;
}

function parseJson(value: string): Record<string, unknown> {
  try {
    const parsed = JSON.parse(value);
    return typeof parsed === 'object' && parsed !== null ? (parsed as Record<string, unknown>) : {};
  } catch {
    return {};
  }
}

function mergeProvenance(
  predictorExecutions: readonly unknown[],
  details: ReadonlyArray<{
    candidate: { predictionObservations: Array<{ predictorExecution?: Record<string, unknown> }> };
  }>,
): Record<string, unknown>[] {
  const byId = new Map<string, Record<string, unknown>>();
  for (const execution of predictorExecutions.map(plainRecord)) {
    if (typeof execution.id === 'string') byId.set(execution.id, execution);
  }
  for (const detail of details) {
    for (const observation of detail.candidate.predictionObservations) {
      const execution = plainRecord(observation.predictorExecution);
      if (typeof execution.id === 'string') byId.set(execution.id, execution);
    }
  }
  return [...byId.values()];
}

function predictionBundle(
  candidateType: string,
  observations: readonly unknown[],
  candidates: ReadonlyArray<{ id: string; candidateType: string }>,
  provenance: readonly Record<string, unknown>[],
) {
  const candidateIds = new Set(
    candidates.filter((candidate) => candidate.candidateType === candidateType).map(({ id }) => id),
  );
  return {
    schemaVersion: 'immunograph-predictions.v1',
    candidateType,
    observations: observations
      .map(plainRecord)
      .filter((observation) => candidateIds.has(String(observation.candidateId))),
    provenance,
  };
}

function candidateEvidenceLinks(
  details: ReadonlyArray<{
    candidate: {
      id: string;
      predictionObservations: Array<{ id?: string }>;
      constraintOutcomes?: Array<{ id?: string }>;
      evidenceSummaries?: Array<{ id?: string }>;
    };
  }>,
) {
  return details.map(({ candidate }) => ({
    candidateId: candidate.id,
    observationIds: candidate.predictionObservations.map(({ id }) => id).filter(Boolean),
    constraintOutcomeIds: (candidate.constraintOutcomes ?? []).map(({ id }) => id).filter(Boolean),
    evidenceSummaryIds: (candidate.evidenceSummaries ?? []).map(({ id }) => id).filter(Boolean),
  }));
}

function candidatesCsv(rows: Array<Record<string, unknown>>): string {
  const columns = [
    'rank',
    'track',
    'peptide',
    'start',
    'end',
    'allele',
    'finalScore',
    'category',
    'sourceStatus',
    'scientificUse',
  ];
  return `${columns.join(',')}\n${rows
    .map((row) => columns.map((column) => csvCell(row[column])).join(','))
    .join('\n')}\n`;
}

function csvCell(value: unknown): string {
  return `"${String(value ?? '').replaceAll('"', '""')}"`;
}

function constructFasta(runId: string, ranked: Array<Record<string, unknown>>): string {
  const selected = ranked.filter((row) => row.category === 'RECOMMENDED');
  const sequence = selected
    .map((row) => String(row.peptide ?? plainRecord(row.candidate).peptide ?? ''))
    .filter((peptide) => peptide.length > 0)
    .join('GGGS');
  return sequence.length > 0
    ? `>immunograph_${runId}_research_construct\n${sequence}\n`
    : `>immunograph_${runId}_no_construct_generated\n`;
}
