import { createHash } from 'node:crypto';

import type { Repositories } from '@immunograph/database';
import { z } from 'zod';

import type { ArtifactStore } from './artifact-store.js';
import { DependencyUnavailableError } from './errors.js';
import { isFallbackEligible } from './execution-policy.js';
import type { McpToolGateway } from './mcp-tool-gateway.js';
import type { ReportGenerationCommand, ReportGenerationPort } from './ports.js';
import { createResearchPackageArtifact } from './research-package-artifact.js';
import { createSupplementalReportArtifacts } from './report-artifacts.js';

const sha256 = z.string().regex(/^[a-f0-9]{64}$/);
const reportDataSchema = z.object({
  artifacts: z
    .array(
      z.object({
        artifactId: z.string().min(1),
        mediaType: z.string().min(1),
        sha256,
        byteLength: z.number().int().nonnegative(),
        reference: z.string().min(1),
        contentBase64: z.string().min(1).optional(),
      }),
    )
    .min(1),
  disclaimer: z.string().min(1),
  provenanceSummary: z.record(z.unknown()),
  runQuality: z.string().min(1),
});

const SYNTHETIC_REPORT_DISCLAIMER =
  'This analysis was produced using the deterministic offline demonstration workflow. Binding scores generated by synthetic predictors are for software demonstration only and must not be interpreted as validated scientific predictions.';

type ReportRepositories = Pick<
  Repositories,
  | 'runs'
  | 'projects'
  | 'proteins'
  | 'candidates'
  | 'rankingResults'
  | 'predictorExecutions'
  | 'observations'
  | 'populationCoverageResults'
  | 'shortlistOptimizationResults'
  | 'approvals'
  | 'artifacts'
  | 'events'
  | 'graphEdges'
  | 'graphNodes'
  | 'stages'
>;

export class McpReportGenerationPort implements ReportGenerationPort {
  constructor(
    private readonly repositories: ReportRepositories,
    private readonly artifactStore: ArtifactStore,
    private readonly gateway: McpToolGateway,
    private readonly fallback: ReportGenerationPort,
  ) {}

  assertAvailable(): Promise<void> {
    return Promise.resolve();
  }

  async generate(command: ReportGenerationCommand) {
    try {
      const run = await this.repositories.runs.findById(command.runId);
      if (run === null) throw new DependencyUnavailableError('report run');
      const snapshotHash = await this.repositories.rankingResults.findLatestSnapshotHash(
        command.runId,
      );
      if (snapshotHash === null) throw new DependencyUnavailableError('ranking snapshot');
      const rankings = await this.repositories.rankingResults.findSnapshot(
        command.runId,
        snapshotHash,
      );
      const rows = [];
      for (const ranking of rankings) {
        const detail = await this.repositories.candidates.findDetail(
          command.runId,
          ranking.candidateId,
          snapshotHash,
        );
        if (detail === null) continue;
        const statuses = detail.candidate.predictionObservations.map(
          ({ predictorExecution }) => predictorExecution.sourceStatus,
        );
        rows.push({
          rank: ranking.rank,
          track: ranking.track,
          peptide: detail.candidate.peptide,
          start: detail.candidate.start,
          end: detail.candidate.end,
          allele: detail.candidate.allele,
          finalScore: ranking.finalScore,
          category: ranking.category,
          sourceStatus: statuses.join('+'),
          scientificUse: statuses.length > 0 && statuses.every((status) => status === 'LIVE'),
        });
      }
      const executionMode = run.executionMode ?? 'FIXTURE';
      const scientificUse = executionMode === 'LIVE';
      const disclaimer = scientificUse
        ? 'Computational predictions require independent scientific validation before research or clinical interpretation.'
        : SYNTHETIC_REPORT_DISCLAIMER;
      const response = await this.gateway.call(
        'generate_report',
        {
          runId: command.runId,
          templateVersion: command.options.templateVersion,
          outputFormats: command.options.formats,
          idempotencyKey: command.requestId,
          reportSnapshot: {
            executionMode,
            runQuality: run.quality ?? 'PARTIAL',
            scientificUse,
            disclaimer,
            candidates: rows,
          },
        },
        reportDataSchema,
        { runId: command.runId, requestId: command.requestId },
      );
      const created = [];
      const suffix = command.requestId.replace(/[^a-zA-Z0-9-]/g, '').slice(0, 36) || 'mcp';
      for (const [index, artifact] of response.data.artifacts.entries()) {
        if (artifact.contentBase64 === undefined) {
          throw new DependencyUnavailableError('MCP report artifact content');
        }
        const bytes = Buffer.from(artifact.contentBase64, 'base64');
        if (
          bytes.byteLength !== artifact.byteLength ||
          createHash('sha256').update(bytes).digest('hex') !== artifact.sha256
        ) {
          throw new DependencyUnavailableError('MCP report artifact integrity');
        }
        const format = command.options.formats[index];
        if (format === undefined) throw new DependencyUnavailableError('MCP report format');
        const relativePath = `${command.runId}/report-${snapshotHash.slice(0, 12)}-${suffix}.${format.toLowerCase()}`;
        const file = await this.artifactStore.write(
          relativePath,
          bytes.toString('utf8'),
          artifact.mediaType,
        );
        created.push(
          await this.repositories.artifacts.create({
            runId: command.runId,
            type: format,
            format,
            ...file,
            templateVersion: command.options.templateVersion,
          }),
        );
      }
      await createSupplementalReportArtifacts(this.repositories, this.artifactStore, {
        runId: command.runId,
        rankingSnapshotHash: snapshotHash,
        requestSuffix: suffix,
        templateVersion: command.options.templateVersion,
        includeEvidenceGraph: command.options.includeEvidenceGraph,
        includeWorkflowTrace: command.options.includeWorkflowTrace,
      });
      await createResearchPackageArtifact(this.repositories, this.artifactStore, {
        runId: command.runId,
        rankingSnapshotHash: snapshotHash,
        requestSuffix: suffix,
        templateVersion: command.options.templateVersion,
      });
      const first = created[0];
      if (first === undefined) throw new DependencyUnavailableError('MCP report output');
      return { artifactJobId: first.id, status: 'QUEUED' as const };
    } catch (error) {
      if (!isFallbackEligible(error)) throw error;
      return this.fallback.generate(command);
    }
  }
}
